version: '3.1'

services:
  postgres:
    container_name: sphub_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sphub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'